[options]
admin_passwd = superadmin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
list_db = True
db_template = template0
logfile = /var/log/odoo/odoo.log
limit_time_cpu = 1200
limit_time_real = 2400
