/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TestResolveRouteImport } from './routes/test-resolve'
import { Route as AppAppsMarketplaceRouteImport } from './routes/_app/apps-marketplace'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppGrowRouteImport } from './routes/_app/grow'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppShopSettingsRouteImport } from './routes/_app/shop-settings'
import { Route as AppSubscriptionRouteImport } from './routes/_app/subscription'
import { Route as OpenAppSlugRouteImport } from './routes/open-app/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResolveRoute = TestResolveRouteImport.update({
  id: '/test-resolve',
  path: '/test-resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppsMarketplaceRoute = AppAppsMarketplaceRouteImport.update({
  id: '/apps-marketplace',
  path: '/apps-marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowRoute = AppGrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppShopSettingsRoute = AppShopSettingsRouteImport.update({
  id: '/shop-settings',
  path: '/shop-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const OpenAppSlugRoute = OpenAppSlugRouteImport.update({
  id: '/open-app/$slug',
  path: '/open-app/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/test-resolve': typeof TestResolveRoute
  '/apps-marketplace': typeof AppAppsMarketplaceRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/grow': typeof AppGrowRoute
  '/profile': typeof AppProfileRoute
  '/shop-settings': typeof AppShopSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/open-app/$slug': typeof OpenAppSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/test-resolve': typeof TestResolveRoute
  '/apps-marketplace': typeof AppAppsMarketplaceRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/grow': typeof AppGrowRoute
  '/profile': typeof AppProfileRoute
  '/shop-settings': typeof AppShopSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/open-app/$slug': typeof OpenAppSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/test-resolve': typeof TestResolveRoute
  '/_app/apps-marketplace': typeof AppAppsMarketplaceRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/grow': typeof AppGrowRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/shop-settings': typeof AppShopSettingsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/open-app/$slug': typeof OpenAppSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/test-resolve'
    | '/apps-marketplace'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/grow'
    | '/profile'
    | '/shop-settings'
    | '/subscription'
    | '/open-app/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/test-resolve'
    | '/apps-marketplace'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/grow'
    | '/profile'
    | '/shop-settings'
    | '/subscription'
    | '/open-app/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/test-resolve'
    | '/_app/apps-marketplace'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/grow'
    | '/_app/profile'
    | '/_app/shop-settings'
    | '/_app/subscription'
    | '/open-app/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  TestResolveRoute: typeof TestResolveRoute
  OpenAppSlugRoute: typeof OpenAppSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-resolve': {
      id: '/test-resolve'
      path: '/test-resolve'
      fullPath: '/test-resolve'
      preLoaderRoute: typeof TestResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/apps-marketplace': {
      id: '/_app/apps-marketplace'
      path: '/apps-marketplace'
      fullPath: '/apps-marketplace'
      preLoaderRoute: typeof AppAppsMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grow': {
      id: '/_app/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof AppGrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop-settings': {
      id: '/_app/shop-settings'
      path: '/shop-settings'
      fullPath: '/shop-settings'
      preLoaderRoute: typeof AppShopSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/open-app/$slug': {
      id: '/open-app/$slug'
      path: '/open-app/$slug'
      fullPath: '/open-app/$slug'
      preLoaderRoute: typeof OpenAppSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAppsMarketplaceRoute: typeof AppAppsMarketplaceRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppGrowRoute: typeof AppGrowRoute
  AppProfileRoute: typeof AppProfileRoute
  AppShopSettingsRoute: typeof AppShopSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppsMarketplaceRoute: AppAppsMarketplaceRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppGrowRoute: AppGrowRoute,
  AppProfileRoute: AppProfileRoute,
  AppShopSettingsRoute: AppShopSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  TestResolveRoute: TestResolveRoute,
  OpenAppSlugRoute: OpenAppSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
